package ru.r2cloud.satellite;

import java.io.IOException;
import java.io.InputStream;
import java.util.Arrays;

public class AutoGeneratedBytes extends InputStream {

	private int doublesReturned = 0;

	private byte[] currentDouble;
	private int currentIndexInDouble = 0;

	@Override
	public int read() throws IOException {
		if (currentDouble == null || currentIndexInDouble >= currentDouble.length) {
			if (doublesReturned >= 60000) {
				return -1;
			}
			currentIndexInDouble = 0;
			currentDouble = new byte[16];
			// first number is always 0
			Arrays.fill(currentDouble, (byte) 0);
			byte[] number = writeLong(Double.doubleToLongBits(Math.sin((doublesReturned % 4) * 90.0)));
			System.arraycopy(number, 0, currentDouble, 8, number.length);
			doublesReturned++;
		}
		int result = currentDouble[currentIndexInDouble];
		currentIndexInDouble++;
		return result;
	}

	private static final byte[] writeLong(long v) {
		byte[] writeBuffer = new byte[8];
		writeBuffer[0] = (byte) (v >>> 56);
		writeBuffer[1] = (byte) (v >>> 48);
		writeBuffer[2] = (byte) (v >>> 40);
		writeBuffer[3] = (byte) (v >>> 32);
		writeBuffer[4] = (byte) (v >>> 24);
		writeBuffer[5] = (byte) (v >>> 16);
		writeBuffer[6] = (byte) (v >>> 8);
		writeBuffer[7] = (byte) (v >>> 0);
		return writeBuffer;
	}

}
